-- Migration: OpenAI embeddings (1536 dims) → multilingual-e5-large (1024 dims)
-- Run this in the Supabase SQL console

-- 1. Drop existing HNSW indexes
DROP INDEX IF EXISTS job_postings_embedding_idx;
DROP INDEX IF EXISTS candidates_embedding_idx;

-- 2. Resize embedding columns (1536 → 1024)
-- NOTE: existing embeddings are lost and must be regenerated by the Celery worker
ALTER TABLE job_postings DROP COLUMN IF EXISTS embedding;
ALTER TABLE job_postings ADD COLUMN embedding vector(1024);

ALTER TABLE candidates DROP COLUMN IF EXISTS embedding;
ALTER TABLE candidates ADD COLUMN embedding vector(1024);

-- 3. Recreate HNSW indexes
CREATE INDEX job_postings_embedding_idx ON job_postings USING hnsw (embedding vector_cosine_ops);
CREATE INDEX candidates_embedding_idx ON candidates USING hnsw (embedding vector_cosine_ops);

-- 4. Update the RPC function to use the new vector dimension
CREATE OR REPLACE FUNCTION match_candidates_for_job(
    query_embedding vector(1024),
    match_job_id uuid,
    match_threshold float,
    match_count int
)
RETURNS TABLE (
    id uuid,
    name text,
    email text,
    profile_text text,
    cv_url text,
    created_at timestamptz,
    similarity float
)
LANGUAGE sql
AS $$
    SELECT
        c.id,
        c.name,
        c.email,
        c.profile_text,
        c.cv_url,
        c.created_at,
        1 - (c.embedding <=> query_embedding) AS similarity
    FROM candidates c
    JOIN screenings s ON s.candidate_id = c.id
    WHERE s.job_posting_id = match_job_id
      AND 1 - (c.embedding <=> query_embedding) > match_threshold
    ORDER BY c.embedding <=> query_embedding
    LIMIT match_count;
$$;
