/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as CandidateOnboardingRouteImport } from './routes/candidate/onboarding'
import { Route as CandidateLoginRouteImport } from './routes/candidate/login'
import { Route as CandidateDashboardRouteImport } from './routes/candidate/dashboard'
import { Route as CandidateCoachRouteImport } from './routes/candidate/coach'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs/$jobId.apply'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateOnboardingRoute = CandidateOnboardingRouteImport.update({
  id: '/candidate/onboarding',
  path: '/candidate/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateLoginRoute = CandidateLoginRouteImport.update({
  id: '/candidate/login',
  path: '/candidate/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateCoachRoute = CandidateCoachRouteImport.update({
  id: '/candidate/coach',
  path: '/candidate/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/candidate/coach': typeof CandidateCoachRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/candidate/coach': typeof CandidateCoachRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/candidate/coach': typeof CandidateCoachRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/candidate/coach'
    | '/candidate/dashboard'
    | '/candidate/login'
    | '/candidate/onboarding'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/'
    | '/jobs/$jobId/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/candidate/coach'
    | '/candidate/dashboard'
    | '/candidate/login'
    | '/candidate/onboarding'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs'
    | '/jobs/$jobId/apply'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/candidate/coach'
    | '/candidate/dashboard'
    | '/candidate/login'
    | '/candidate/onboarding'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/'
    | '/jobs/$jobId/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  CandidateCoachRoute: typeof CandidateCoachRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateLoginRoute: typeof CandidateLoginRoute
  CandidateOnboardingRoute: typeof CandidateOnboardingRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/onboarding': {
      id: '/candidate/onboarding'
      path: '/candidate/onboarding'
      fullPath: '/candidate/onboarding'
      preLoaderRoute: typeof CandidateOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/login': {
      id: '/candidate/login'
      path: '/candidate/login'
      fullPath: '/candidate/login'
      preLoaderRoute: typeof CandidateLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/coach': {
      id: '/candidate/coach'
      path: '/candidate/coach'
      fullPath: '/candidate/coach'
      preLoaderRoute: typeof CandidateCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  CandidateCoachRoute: CandidateCoachRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateLoginRoute: CandidateLoginRoute,
  CandidateOnboardingRoute: CandidateOnboardingRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
